//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm.Toolkit.ImitationTelerik {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orm.Toolkit.ImitationTelerik.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 活动行 的本地化字符串。
        /// </summary>
        internal static string ActivateRow {
            get {
                return ResourceManager.GetString("ActivateRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All da_y event 的本地化字符串。
        /// </summary>
        internal static string AllDayEvent {
            get {
                return ResourceManager.GetString("AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        internal static string AppearanceCategory {
            get {
                return ResourceManager.GetString("AppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appointment 的本地化字符串。
        /// </summary>
        internal static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appointment Recurrence 的本地化字符串。
        /// </summary>
        internal static string AppointmentRecurrence {
            get {
                return ResourceManager.GetString("AppointmentRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appointment time 的本地化字符串。
        /// </summary>
        internal static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto hide 的本地化字符串。
        /// </summary>
        internal static string Auto_hide {
            get {
                return ResourceManager.GetString("Auto_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin Edit 的本地化字符串。
        /// </summary>
        internal static string BeginEdit {
            get {
                return ResourceManager.GetString("BeginEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin Insert 的本地化字符串。
        /// </summary>
        internal static string BeginInsert {
            get {
                return ResourceManager.GetString("BeginInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        internal static string BehaviourCategory {
            get {
                return ResourceManager.GetString("BehaviourCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brushes 的本地化字符串。
        /// </summary>
        internal static string BrushesCategory {
            get {
                return ResourceManager.GetString("BrushesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Busy 的本地化字符串。
        /// </summary>
        internal static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Cell Edit 的本地化字符串。
        /// </summary>
        internal static string CancelCellEdit {
            get {
                return ResourceManager.GetString("CancelCellEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Row Edit 的本地化字符串。
        /// </summary>
        internal static string CancelRowEdit {
            get {
                return ResourceManager.GetString("CancelRowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bring to front popup with different type. 的本地化字符串。
        /// </summary>
        internal static string CannotBringToFrontDifferentTypes {
            get {
                return ResourceManager.GetString("CannotBringToFrontDifferentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot change starting ZIndex when there are open Popup. 的本地化字符串。
        /// </summary>
        internal static string CannotChangeStartingIndex {
            get {
                return ResourceManager.GetString("CannotChangeStartingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items collection must be empty before using ItemsSource. 的本地化字符串。
        /// </summary>
        internal static string CannotUseItemsSource {
            get {
                return ResourceManager.GetString("CannotUseItemsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Categorize 的本地化字符串。
        /// </summary>
        internal static string Categorize {
            get {
                return ResourceManager.GetString("Categorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dddd, dd MMMM yyyy 的本地化字符串。
        /// </summary>
        internal static string ChartAxisLabelDateTimeFormat {
            get {
                return ResourceManager.GetString("ChartAxisLabelDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ChartAxisLabelFormat {
            get {
                return ResourceManager.GetString("ChartAxisLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string ChartChartLegendHeader {
            get {
                return ResourceManager.GetString("ChartChartLegendHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series {0} 的本地化字符串。
        /// </summary>
        internal static string ChartChartLegendLinearSeriesFormat {
            get {
                return ResourceManager.GetString("ChartChartLegendLinearSeriesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item {0} 的本地化字符串。
        /// </summary>
        internal static string ChartChartLegendRadialSeriesFormat {
            get {
                return ResourceManager.GetString("ChartChartLegendRadialSeriesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ChartChartTitle {
            get {
                return ResourceManager.GetString("ChartChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ChartHorizontalAxisTitle {
            get {
                return ResourceManager.GetString("ChartHorizontalAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ChartItemLabelFormat {
            get {
                return ResourceManager.GetString("ChartItemLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ChartItemToolTipFormat {
            get {
                return ResourceManager.GetString("ChartItemToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Data Series. 的本地化字符串。
        /// </summary>
        internal static string ChartNoDataMessage {
            get {
                return ResourceManager.GetString("ChartNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High: {0}{2}Low: {1} 的本地化字符串。
        /// </summary>
        internal static string ChartRangeItemToolTipFormat {
            get {
                return ResourceManager.GetString("ChartRangeItemToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High: {0}{4}Low: {1}{4}Open: {2}{4}Close: {3} 的本地化字符串。
        /// </summary>
        internal static string ChartStickItemToolTipFormat {
            get {
                return ResourceManager.GetString("ChartStickItemToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ChartVerticalAxisTitle {
            get {
                return ResourceManager.GetString("ChartVerticalAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All 的本地化字符串。
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseItem {
            get {
                return ResourceManager.GetString("CloseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to close this dialog without saving the changes? 的本地化字符串。
        /// </summary>
        internal static string CloseItemQuestion {
            get {
                return ResourceManager.GetString("CloseItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        internal static string CollapseHierarchyItem {
            get {
                return ResourceManager.GetString("CollapseHierarchyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        internal static string ColorPickerAutomatic {
            get {
                return ResourceManager.GetString("ColorPickerAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard colors 的本地化字符串。
        /// </summary>
        internal static string ColorPickerStandardColors {
            get {
                return ResourceManager.GetString("ColorPickerStandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme colors 的本地化字符串。
        /// </summary>
        internal static string ColorPickerThemeColors {
            get {
                return ResourceManager.GetString("ColorPickerThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit Edit 的本地化字符串。
        /// </summary>
        internal static string CommitEdit {
            get {
                return ResourceManager.GetString("CommitEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common Properties 的本地化字符串。
        /// </summary>
        internal static string CommonCategory {
            get {
                return ResourceManager.GetString("CommonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string ContentCategory {
            get {
                return ResourceManager.GetString("ContentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that represents the degree (in pixels) to which the corners of a Border are rounded. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ControlCornerRadius {
            get {
                return ResourceManager.GetString("ControlCornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets whether the control is highlighted (like in mouse-over case). This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ControlIsHighlighted {
            get {
                return ResourceManager.GetString("ControlIsHighlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets whether the mouse is over. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ControlIsMouseOver {
            get {
                return ResourceManager.GetString("ControlIsMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets whether the state is pressed. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ControlIsPressed {
            get {
                return ResourceManager.GetString("ControlIsPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create appointment 的本地化字符串。
        /// </summary>
        internal static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Daily 的本地化字符串。
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day(s) 的本地化字符串。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete appointment 的本地化字符串。
        /// </summary>
        internal static string DeleteAppointment {
            get {
                return ResourceManager.GetString("DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete item 的本地化字符串。
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this appointment? 的本地化字符串。
        /// </summary>
        internal static string DeleteItemQuestion {
            get {
                return ResourceManager.GetString("DeleteItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this _occurrence. 的本地化字符串。
        /// </summary>
        internal static string DeleteOccurrence {
            get {
                return ResourceManager.GetString("DeleteOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Recurring Item 的本地化字符串。
        /// </summary>
        internal static string DeleteRecurringItem {
            get {
                return ResourceManager.GetString("DeleteRecurringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is a recurring appointment. Do you want to delete only this occurrence or the series? 的本地化字符串。
        /// </summary>
        internal static string DeleteRecurringItemQuestion {
            get {
                return ResourceManager.GetString("DeleteRecurringItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the _series. 的本地化字符串。
        /// </summary>
        internal static string DeleteSeries {
            get {
                return ResourceManager.GetString("DeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dockable 的本地化字符串。
        /// </summary>
        internal static string Dockable {
            get {
                return ResourceManager.GetString("Dockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root AdornerLayer Not Found. Please make sure that your root visual is Window or other element that has an adorner layer. Alternatively, wrap your root panel in an &lt;AdornerDecorator&gt; element. 的本地化字符串。
        /// </summary>
        internal static string DragDropMissingAdornerLayer {
            get {
                return ResourceManager.GetString("DragDropMissingAdornerLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D_uration 的本地化字符串。
        /// </summary>
        internal static string DurationColon {
            get {
                return ResourceManager.GetString("DurationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day 的本地化字符串。
        /// </summary>
        internal static string DurationDay {
            get {
                return ResourceManager.GetString("DurationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 days 的本地化字符串。
        /// </summary>
        internal static string DurationDays {
            get {
                return ResourceManager.GetString("DurationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour 的本地化字符串。
        /// </summary>
        internal static string DurationHour {
            get {
                return ResourceManager.GetString("DurationHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hours 的本地化字符串。
        /// </summary>
        internal static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minute 的本地化字符串。
        /// </summary>
        internal static string DurationMinute {
            get {
                return ResourceManager.GetString("DurationMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minutes 的本地化字符串。
        /// </summary>
        internal static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 week 的本地化字符串。
        /// </summary>
        internal static string DurationWeek {
            get {
                return ResourceManager.GetString("DurationWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weeks 的本地化字符串。
        /// </summary>
        internal static string DurationWeeks {
            get {
                return ResourceManager.GetString("DurationWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Appointment 的本地化字符串。
        /// </summary>
        internal static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Parent Appointment 的本地化字符串。
        /// </summary>
        internal static string EditParentAppointment {
            get {
                return ResourceManager.GetString("EditParentAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Recurrence 的本地化字符串。
        /// </summary>
        internal static string EditRecurrence {
            get {
                return ResourceManager.GetString("EditRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit _Recurrence 的本地化字符串。
        /// </summary>
        internal static string EditRecurrenceCommandText {
            get {
                return ResourceManager.GetString("EditRecurrenceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit recurrence rule 的本地化字符串。
        /// </summary>
        internal static string EditRecurrenceRule {
            get {
                return ResourceManager.GetString("EditRecurrenceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End a_fter 的本地化字符串。
        /// </summary>
        internal static string EndAfter {
            get {
                return ResourceManager.GetString("EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End _by 的本地化字符串。
        /// </summary>
        internal static string EndBy {
            get {
                return ResourceManager.GetString("EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_nd 的本地化字符串。
        /// </summary>
        internal static string EndColon {
            get {
                return ResourceManager.GetString("EndColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The end date you entered occurs before the start date 的本地化字符串。
        /// </summary>
        internal static string EndDateBeforeStart {
            get {
                return ResourceManager.GetString("EndDateBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_very 的本地化字符串。
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day 的本地化字符串。
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every wee_kday 的本地化字符串。
        /// </summary>
        internal static string EveryWeekday {
            get {
                return ResourceManager.GetString("EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use this property to read and initialize when expander will expand. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderClickMode {
            get {
                return ResourceManager.GetString("ExpanderClickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a ControlTemplate used to customize the Expander-decorator item. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderDecoratorTemplate {
            get {
                return ResourceManager.GetString("ExpanderDecoratorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property determines the expand direction of the control. There are four options: Down, Up, Right and Left. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderExpandDirection {
            get {
                return ResourceManager.GetString("ExpanderExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a ControlTemplate used to customize the whole Header part of the Expander. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderHeaderControlTemplate {
            get {
                return ResourceManager.GetString("ExpanderHeaderControlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HorizontalHeaderAlignment determines the horizontal alignment of the Header. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderHorizontalHeaderAlignment {
            get {
                return ResourceManager.GetString("ExpanderHorizontalHeaderAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use this property to permit the animation of the expander&apos;s content. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderIsAnimated {
            get {
                return ResourceManager.GetString("ExpanderIsAnimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use this property to read and initialize expand and collapse states of the Expander. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderIsExpanded {
            get {
                return ResourceManager.GetString("ExpanderIsExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expander will use the template from this property if it is initialized. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderTemplateDown {
            get {
                return ResourceManager.GetString("ExpanderTemplateDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expander will use the template from this property if it is initialized. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderTemplateLeft {
            get {
                return ResourceManager.GetString("ExpanderTemplateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expander will use the template from this property if it is initialized. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderTemplateRight {
            get {
                return ResourceManager.GetString("ExpanderTemplateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expander will use the template from this property if it is initialized. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderTemplateUp {
            get {
                return ResourceManager.GetString("ExpanderTemplateUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VerticalHeaderAlignment determines the vertical alignment of the Header. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ExpanderVerticalHeaderAlignment {
            get {
                return ResourceManager.GetString("ExpanderVerticalHeaderAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string ExpandHierarchyItem {
            get {
                return ResourceManager.GetString("ExpandHierarchyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extends selection to current unit 的本地化字符串。
        /// </summary>
        internal static string ExtendSelectionToCurrentUnit {
            get {
                return ResourceManager.GetString("ExtendSelectionToCurrentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string FilterContains {
            get {
                return ResourceManager.GetString("FilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does not contain 的本地化字符串。
        /// </summary>
        internal static string FilterDoesNotContain {
            get {
                return ResourceManager.GetString("FilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends with 的本地化字符串。
        /// </summary>
        internal static string FilterEndsWith {
            get {
                return ResourceManager.GetString("FilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is contained in 的本地化字符串。
        /// </summary>
        internal static string FilterIsContainedIn {
            get {
                return ResourceManager.GetString("FilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterIsEqualTo {
            get {
                return ResourceManager.GetString("FilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than 的本地化字符串。
        /// </summary>
        internal static string FilterIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than 的本地化字符串。
        /// </summary>
        internal static string FilterIsLessThan {
            get {
                return ResourceManager.GetString("FilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match case 的本地化字符串。
        /// </summary>
        internal static string FilterMatchCase {
            get {
                return ResourceManager.GetString("FilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string FilterOr {
            get {
                return ResourceManager.GetString("FilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts with 的本地化字符串。
        /// </summary>
        internal static string FilterStartsWith {
            get {
                return ResourceManager.GetString("FilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 first 的本地化字符串。
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Floating 的本地化字符串。
        /// </summary>
        internal static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fourth 的本地化字符串。
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free 的本地化字符串。
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to add new item 的本地化字符串。
        /// </summary>
        internal static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filter 的本地化字符串。
        /// </summary>
        internal static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does not contain 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends with 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is contained in 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than or equal to 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than or equal to 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match case 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show rows with value that 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts with 的本地化字符串。
        /// </summary>
        internal static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column header and drop it here to group by that column 的本地化字符串。
        /// </summary>
        internal static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Header 的本地化字符串。
        /// </summary>
        internal static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grouped by: 的本地化字符串。
        /// </summary>
        internal static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the header of the control. 的本地化字符串。
        /// </summary>
        internal static string HeaderContentControl_Header_Description {
            get {
                return ResourceManager.GetString("HeaderContentControl_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the data template for the header. 的本地化字符串。
        /// </summary>
        internal static string HeaderedContentControl_HeaderTemplate_Description {
            get {
                return ResourceManager.GetString("HeaderedContentControl_HeaderTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HasHeader is a read-only dependency property. 的本地化字符串。
        /// </summary>
        internal static string HeaderedContnetControl_OnHasHeaderChanged {
            get {
                return ResourceManager.GetString("HeaderedContnetControl_OnHasHeaderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the item that labels the control. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string HeaderedItemsControlHeaderDescription {
            get {
                return ResourceManager.GetString("HeaderedItemsControlHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Importance 的本地化字符串。
        /// </summary>
        internal static string HighImportance {
            get {
                return ResourceManager.GetString("HighImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Recurrence pattern is not valid. 的本地化字符串。
        /// </summary>
        internal static string InvalidRecurrenceRuleMessage {
            get {
                return ResourceManager.GetString("InvalidRecurrenceRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid pattern 的本地化字符串。
        /// </summary>
        internal static string InvalidRecurrenceRuleTitle {
            get {
                return ResourceManager.GetString("InvalidRecurrenceRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value indicating whether TextSearch is enabled on the ItemsControl instance. 的本地化字符串。
        /// </summary>
        internal static string ItemsControlIsTextSearchEnabled {
            get {
                return ResourceManager.GetString("ItemsControlIsTextSearchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the style for the item containers of the control. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ItemsControlItemContainerStyleDescription {
            get {
                return ResourceManager.GetString("ItemsControlItemContainerStyleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the alignment of text in the control. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ItemsControlTextAlignmentDescription {
            get {
                return ResourceManager.GetString("ItemsControlTextAlignmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the decorations of the text for the items control. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ItemsControlTextDecorationsDescription {
            get {
                return ResourceManager.GetString("ItemsControlTextDecorationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the text wrapping behaviour for the control. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string ItemsControlTextWrappingDescription {
            get {
                return ResourceManager.GetString("ItemsControlTextWrappingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation is not valid while ItemsSource is in use. Access and modify elements with ItemsControl.ItemsSource instead. 的本地化字符串。
        /// </summary>
        internal static string ItemsSourceInUse {
            get {
                return ResourceManager.GetString("ItemsSourceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 last 的本地化字符串。
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string LayoutCategory {
            get {
                return ResourceManager.GetString("LayoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Importance 的本地化字符串。
        /// </summary>
        internal static string LowImportance {
            get {
                return ResourceManager.GetString("LowImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aerial View 的本地化字符串。
        /// </summary>
        internal static string MapAerialCommand {
            get {
                return ResourceManager.GetString("MapAerialCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bird&apos;s Eye View 的本地化字符串。
        /// </summary>
        internal static string MapBirdseyeCommand {
            get {
                return ResourceManager.GetString("MapBirdseyeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E 的本地化字符串。
        /// </summary>
        internal static string MapEastChar {
            get {
                return ResourceManager.GetString("MapEastChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Labels 的本地化字符串。
        /// </summary>
        internal static string MapLabelsVisibleCommand {
            get {
                return ResourceManager.GetString("MapLabelsVisibleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} km 的本地化字符串。
        /// </summary>
        internal static string MapMapScaleKilometerFormat {
            get {
                return ResourceManager.GetString("MapMapScaleKilometerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} m 的本地化字符串。
        /// </summary>
        internal static string MapMapScaleMeterFormat {
            get {
                return ResourceManager.GetString("MapMapScaleMeterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ml 的本地化字符串。
        /// </summary>
        internal static string MapMapScaleMileFormat {
            get {
                return ResourceManager.GetString("MapMapScaleMileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N 的本地化字符串。
        /// </summary>
        internal static string MapNorthChar {
            get {
                return ResourceManager.GetString("MapNorthChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City 的本地化字符串。
        /// </summary>
        internal static string MapPresetZoomLevelCity {
            get {
                return ResourceManager.GetString("MapPresetZoomLevelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neighborhood 的本地化字符串。
        /// </summary>
        internal static string MapPresetZoomLevelNeighborhood {
            get {
                return ResourceManager.GetString("MapPresetZoomLevelNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region 的本地化字符串。
        /// </summary>
        internal static string MapPresetZoomLevelRegion {
            get {
                return ResourceManager.GetString("MapPresetZoomLevelRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string MapPresetZoomLevelState {
            get {
                return ResourceManager.GetString("MapPresetZoomLevelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 World 的本地化字符串。
        /// </summary>
        internal static string MapPresetZoomLevelWorld {
            get {
                return ResourceManager.GetString("MapPresetZoomLevelWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Road View 的本地化字符串。
        /// </summary>
        internal static string MapRoadCommand {
            get {
                return ResourceManager.GetString("MapRoadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S 的本地化字符串。
        /// </summary>
        internal static string MapSouthChar {
            get {
                return ResourceManager.GetString("MapSouthChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W 的本地化字符串。
        /// </summary>
        internal static string MapWestChar {
            get {
                return ResourceManager.GetString("MapWestChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        internal static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 / 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTimeStatusSeparator {
            get {
                return ResourceManager.GetString("MediaPlayerTimeStatusSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipMute {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Chapter 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipNextChapter {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipNextChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipPlay {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Play list 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipPlaylist {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Chapter 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipPreviousChapter {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipPreviousChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipStop {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipTitle {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        internal static string MediaPlayerTooltipVolume {
            get {
                return ResourceManager.GetString("MediaPlayerTooltipVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misc 的本地化字符串。
        /// </summary>
        internal static string MiscCategory {
            get {
                return ResourceManager.GetString("MiscCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Monthly 的本地化字符串。
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 month(s) 的本地化字符串。
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Left 的本地化字符串。
        /// </summary>
        internal static string MoveLeft {
            get {
                return ResourceManager.GetString("MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Next 的本地化字符串。
        /// </summary>
        internal static string MoveNext {
            get {
                return ResourceManager.GetString("MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Previous 的本地化字符串。
        /// </summary>
        internal static string MovePrevious {
            get {
                return ResourceManager.GetString("MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Right 的本地化字符串。
        /// </summary>
        internal static string MoveRight {
            get {
                return ResourceManager.GetString("MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N_o end date 的本地化字符串。
        /// </summary>
        internal static string NoEndDate {
            get {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor settings type should be a type of class which implements the IEditorSettings interface. 的本地化字符串。
        /// </summary>
        internal static string NotAllowedEditorSettings {
            get {
                return ResourceManager.GetString("NotAllowedEditorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 occurrences 的本地化字符串。
        /// </summary>
        internal static string Occurrences {
            get {
                return ResourceManager.GetString("Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of every 的本地化字符串。
        /// </summary>
        internal static string OfEvery {
            get {
                return ResourceManager.GetString("OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open this _occurrence.  的本地化字符串。
        /// </summary>
        internal static string OpenOccurrence {
            get {
                return ResourceManager.GetString("OpenOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Recurring Item 的本地化字符串。
        /// </summary>
        internal static string OpenRecurringItem {
            get {
                return ResourceManager.GetString("OpenRecurringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is a recurring appointment. Do you want to open only this occurrence or the series? 的本地化字符串。
        /// </summary>
        internal static string OpenRecurringItemQuestion {
            get {
                return ResourceManager.GetString("OpenRecurringItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the _series. 的本地化字符串。
        /// </summary>
        internal static string OpenSeries {
            get {
                return ResourceManager.GetString("OpenSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure buttons 的本地化字符串。
        /// </summary>
        internal static string OutlookBarConfigureButtons {
            get {
                return ResourceManager.GetString("OutlookBarConfigureButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start dragging in order to change items&apos; position 的本地化字符串。
        /// </summary>
        internal static string OutlookBarHorizontalSplitter {
            get {
                return ResourceManager.GetString("OutlookBarHorizontalSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out Of Office 的本地化字符串。
        /// </summary>
        internal static string OutOfOffice {
            get {
                return ResourceManager.GetString("OutOfOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identifies the ExpandMode dependency property. 的本地化字符串。
        /// </summary>
        internal static string PanelBarExpandModePropertyDescription {
            get {
                return ResourceManager.GetString("PanelBarExpandModePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies whether an item is selected or not. 的本地化字符串。
        /// </summary>
        internal static string PanelBarIsSelectedPropertyDescription {
            get {
                return ResourceManager.GetString("PanelBarIsSelectedPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadPanelBarItem objects should have a parent of type RadPanelBar! 的本地化字符串。
        /// </summary>
        internal static string PanelBarItemOnApplyTemplateInvalidOperation {
            get {
                return ResourceManager.GetString("PanelBarItemOnApplyTemplateInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadPanelBarItem objects should have a parent of type RadPanelBar! 的本地化字符串。
        /// </summary>
        internal static string PanelBarItemOnApplyTemplateInvalidOperation1 {
            get {
                return ResourceManager.GetString("PanelBarItemOnApplyTemplateInvalidOperation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies the control template for second-level items. 的本地化字符串。
        /// </summary>
        internal static string PanelBarSecondLevelTemplatePropertyDescription {
            get {
                return ResourceManager.GetString("PanelBarSecondLevelTemplatePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identifies the SelectedValuePath dependency property. 的本地化字符串。
        /// </summary>
        internal static string PanelBarSelectedValuePathPropertyDescription {
            get {
                return ResourceManager.GetString("PanelBarSelectedValuePathPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies the control template for top-level items. 的本地化字符串。
        /// </summary>
        internal static string PanelBarTopLevelTemplatePropertyDescription {
            get {
                return ResourceManager.GetString("PanelBarTopLevelTemplatePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup index must be between {0} and {1}. 的本地化字符串。
        /// </summary>
        internal static string PopupIndexOutOfRange {
            get {
                return ResourceManager.GetString("PopupIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        internal static string RadDataPagerEllipsisString {
            get {
                return ResourceManager.GetString("RadDataPagerEllipsisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string RadDataPagerOf {
            get {
                return ResourceManager.GetString("RadDataPagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        internal static string RadDataPagerPage {
            get {
                return ResourceManager.GetString("RadDataPagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range of recurrence 的本地化字符串。
        /// </summary>
        internal static string RangeOfRecurrence {
            get {
                return ResourceManager.GetString("RangeOfRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re_cur every 的本地化字符串。
        /// </summary>
        internal static string RecurEvery {
            get {
                return ResourceManager.GetString("RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurrence pattern 的本地化字符串。
        /// </summary>
        internal static string RecurrencePattern {
            get {
                return ResourceManager.GetString("RecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Recurrence 的本地化字符串。
        /// </summary>
        internal static string RemoveRecurrence {
            get {
                return ResourceManager.GetString("RemoveRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only change the resources by opening the series 的本地化字符串。
        /// </summary>
        internal static string ResourceEditingMessage {
            get {
                return ResourceManager.GetString("ResourceEditingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        internal static string RibbonBarGalleryButtonMore {
            get {
                return ResourceManager.GetString("RibbonBarGalleryButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row  的本地化字符串。
        /// </summary>
        internal static string RibbonBarGalleryButtonUpDown {
            get {
                return ResourceManager.GetString("RibbonBarGalleryButtonUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize Quick Access Tool bar 的本地化字符串。
        /// </summary>
        internal static string RibbonBarQATCustomize {
            get {
                return ResourceManager.GetString("RibbonBarQATCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonBarQATMinimize {
            get {
                return ResourceManager.GetString("RibbonBarQATMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show above the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonBarQATShowAbove {
            get {
                return ResourceManager.GetString("RibbonBarQATShowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show below the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonBarQATShowBelow {
            get {
                return ResourceManager.GetString("RibbonBarQATShowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -  的本地化字符串。
        /// </summary>
        internal static string RibbonBarWindowTitleDivider {
            get {
                return ResourceManager.GetString("RibbonBarWindowTitleDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and Close 的本地化字符串。
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save &amp; Close 的本地化字符串。
        /// </summary>
        internal static string SaveAndCloseCommandText {
            get {
                return ResourceManager.GetString("SaveAndCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Appointment 的本地化字符串。
        /// </summary>
        internal static string SaveAppointment {
            get {
                return ResourceManager.GetString("SaveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Recurrence Rule 的本地化字符串。
        /// </summary>
        internal static string SaveRecurrence {
            get {
                return ResourceManager.GetString("SaveRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 second 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Current Item 的本地化字符串。
        /// </summary>
        internal static string SelectCurrentItem {
            get {
                return ResourceManager.GetString("SelectCurrentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the current unit 的本地化字符串。
        /// </summary>
        internal static string SelectCurrentUnit {
            get {
                return ResourceManager.GetString("SelectCurrentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the scheduler&apos;s view mode to day 的本地化字符串。
        /// </summary>
        internal static string SetDayViewMode {
            get {
                return ResourceManager.GetString("SetDayViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the scheduler&apos;s view mode to month 的本地化字符串。
        /// </summary>
        internal static string SetMonthViewMode {
            get {
                return ResourceManager.GetString("SetMonthViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the scheduler&apos;s view mode to timeline 的本地化字符串。
        /// </summary>
        internal static string SetTimelineViewMode {
            get {
                return ResourceManager.GetString("SetTimelineViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the scheduler&apos;s view mode to week 的本地化字符串。
        /// </summary>
        internal static string SetWeekViewMode {
            get {
                return ResourceManager.GetString("SetWeekViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show As 的本地化字符串。
        /// </summary>
        internal static string ShowAs {
            get {
                return ResourceManager.GetString("ShowAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start: 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S_tart 的本地化字符串。
        /// </summary>
        internal static string StartColon {
            get {
                return ResourceManager.GetString("StartColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time 的本地化字符串。
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value for WindowClose enum. 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sub_ject 的本地化字符串。
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabbed document 的本地化字符串。
        /// </summary>
        internal static string Tabbed_document {
            get {
                return ResourceManager.GetString("Tabbed_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the align of the TabItems - Left, Right, Center, Justify. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_Align_Description {
            get {
                return ResourceManager.GetString("TabControl_Align_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets whether all the present tabs have equal height. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_AllTabsEqualHeight_Description {
            get {
                return ResourceManager.GetString("TabControl_AllTabsEqualHeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the opacity of the Background of the TabControl. 的本地化字符串。
        /// </summary>
        internal static string TabControl_BackgroundOpacity_Description {
            get {
                return ResourceManager.GetString("TabControl_BackgroundOpacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the content template to use for displaying the content of the items. 的本地化字符串。
        /// </summary>
        internal static string TabControl_ContentTemplate_Description {
            get {
                return ResourceManager.GetString("TabControl_ContentTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectedContent is a read-only dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_OnSelectedContentChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("TabControl_OnSelectedContentChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectedContentTemplate is a read-only dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_OnSelectedContentTemplateChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("TabControl_OnSelectedContentTemplateChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the orientation of the TabItems in the TabStrip. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_Orientation_Description {
            get {
                return ResourceManager.GetString("TabControl_Orientation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the Position of the TabStrip with regard to the content. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_Position_Description {
            get {
                return ResourceManager.GetString("TabControl_Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets whether the TabItem rows should be reordered when selected. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_ReorderTabRows_Description {
            get {
                return ResourceManager.GetString("TabControl_ReorderTabRows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Gets or sets the index of the selected item. The default value is -1 which means that no item is selected. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_SelectedIndex_Description {
            get {
                return ResourceManager.GetString("TabControl_SelectedIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the currently selected tab. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControl_SelectedTab_Description {
            get {
                return ResourceManager.GetString("TabControl_SelectedTab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabControl when the TabStripPlacement is set to Bottom. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControlBottomTemplateDescription {
            get {
                return ResourceManager.GetString("TabControlBottomTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabControl when the TabStripPlacement is set to LeftThis is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControlLeftTemplateDescription {
            get {
                return ResourceManager.GetString("TabControlLeftTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabControl when the TabStripPlacement is set to RightThis is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControlRightTemplateDescription {
            get {
                return ResourceManager.GetString("TabControlRightTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabControl when the TabStripPlacement is set to Top. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabControlTopTemplateDescription {
            get {
                return ResourceManager.GetString("TabControlTopTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index is a read-only dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItem_OnIndexChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("TabItem_OnIndexChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsMouseOver is a read-only dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItem_OnIsMouseOverChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("TabItem_OnIsMouseOverChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsSelected is a read-only dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItem_OnIsSelectedChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("TabItem_OnIsSelectedChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabItem when the TabStripPlacement is set to Bottom. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItemBottomTemplateDescription {
            get {
                return ResourceManager.GetString("TabItemBottomTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabItem when the TabStripPlacement is set to Left. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItemLeftTemplateDescription {
            get {
                return ResourceManager.GetString("TabItemLeftTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabItem when the TabStripPlacement is set to Right. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItemRightTemplateDescription3 {
            get {
                return ResourceManager.GetString("TabItemRightTemplateDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the template of the TabItem when the TabStripPlacement is set to Top. This is a dependency property. 的本地化字符串。
        /// </summary>
        internal static string TabItemTopTemplateDescription {
            get {
                return ResourceManager.GetString("TabItemTopTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tentative 的本地化字符串。
        /// </summary>
        internal static string Tentative {
            get {
                return ResourceManager.GetString("Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string TextCategory {
            get {
                return ResourceManager.GetString("TextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Th_e 的本地化字符串。
        /// </summary>
        internal static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 third 的本地化字符串。
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        internal static string TileViewItemMaximizeText {
            get {
                return ResourceManager.GetString("TileViewItemMaximizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        internal static string TileViewItemMinimizeText {
            get {
                return ResourceManager.GetString("TileViewItemMinimizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间轴 的本地化字符串。
        /// </summary>
        internal static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform 的本地化字符串。
        /// </summary>
        internal static string TransformCategory {
            get {
                return ResourceManager.GetString("TransformCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop after  的本地化字符串。
        /// </summary>
        internal static string TreeViewDropAfter {
            get {
                return ResourceManager.GetString("TreeViewDropAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop before  的本地化字符串。
        /// </summary>
        internal static string TreeViewDropBefore {
            get {
                return ResourceManager.GetString("TreeViewDropBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop in  的本地化字符串。
        /// </summary>
        internal static string TreeViewDropIn {
            get {
                return ResourceManager.GetString("TreeViewDropIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop as root 的本地化字符串。
        /// </summary>
        internal static string TreeViewDropRoot {
            get {
                return ResourceManager.GetString("TreeViewDropRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Files and Folders are accepted as Drop-data. 的本地化字符串。
        /// </summary>
        internal static string UploadAcceptableDropEntities {
            get {
                return ResourceManager.GetString("UploadAcceptableDropEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string UploadBrowse {
            get {
                return ResourceManager.GetString("UploadBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add more files 的本地化字符串。
        /// </summary>
        internal static string UploadBrowseAppend {
            get {
                return ResourceManager.GetString("UploadBrowseAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BufferSize too big. Please set it to a smaller value. 的本地化字符串。
        /// </summary>
        internal static string UploadBufferSizeSoBig {
            get {
                return ResourceManager.GetString("UploadBufferSizeSoBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string UploadCancel {
            get {
                return ResourceManager.GetString("UploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select files to upload 的本地化字符串。
        /// </summary>
        internal static string UploadCaptionSelect {
            get {
                return ResourceManager.GetString("UploadCaptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Files: 的本地化字符串。
        /// </summary>
        internal static string UploadCaptionSelected {
            get {
                return ResourceManager.GetString("UploadCaptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Done 的本地化字符串。
        /// </summary>
        internal static string UploadCaptionUploaded {
            get {
                return ResourceManager.GetString("UploadCaptionUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading... 的本地化字符串。
        /// </summary>
        internal static string UploadCaptionUploading {
            get {
                return ResourceManager.GetString("UploadCaptionUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not upload an entity of type  的本地化字符串。
        /// </summary>
        internal static string UploadForbiddenDropEntities {
            get {
                return ResourceManager.GetString("UploadForbiddenDropEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handler not found or execution of the handler failed! 的本地化字符串。
        /// </summary>
        internal static string UploadHandlerNotFoundOrFailed {
            get {
                return ResourceManager.GetString("UploadHandlerNotFoundOrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item dismissed. 的本地化字符串。
        /// </summary>
        internal static string UploadItemDismissed {
            get {
                return ResourceManager.GetString("UploadItemDismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string UploadPause {
            get {
                return ResourceManager.GetString("UploadPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some of selected files are restricted by: 的本地化字符串。
        /// </summary>
        internal static string UploadRestriction {
            get {
                return ResourceManager.GetString("UploadRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max number of uploaded files; 的本地化字符串。
        /// </summary>
        internal static string UploadRestrictionCount {
            get {
                return ResourceManager.GetString("UploadRestrictionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max file size; 的本地化字符串。
        /// </summary>
        internal static string UploadRestrictionSize {
            get {
                return ResourceManager.GetString("UploadRestrictionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total size of all uploaded files; 的本地化字符串。
        /// </summary>
        internal static string UploadRestrictionTotalSize {
            get {
                return ResourceManager.GetString("UploadRestrictionTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        internal static string UploadResume {
            get {
                return ResourceManager.GetString("UploadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string UploadTotal {
            get {
                return ResourceManager.GetString("UploadTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error! 的本地化字符串。
        /// </summary>
        internal static string UploadUnknownError {
            get {
                return ResourceManager.GetString("UploadUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        internal static string UploadUpload {
            get {
                return ResourceManager.GetString("UploadUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid upload url. Please make sure the url is absolute! 的本地化字符串。
        /// </summary>
        internal static string UploadUploadServiceUrlInvalidPropertyValue {
            get {
                return ResourceManager.GetString("UploadUploadServiceUrlInvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property UploadServiceUrl not set 的本地化字符串。
        /// </summary>
        internal static string UploadUploadServiceUrlSetProperty {
            get {
                return ResourceManager.GetString("UploadUploadServiceUrlSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekday 的本地化字符串。
        /// </summary>
        internal static string WeekDays {
            get {
                return ResourceManager.GetString("WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekend day 的本地化字符串。
        /// </summary>
        internal static string WeekendDays {
            get {
                return ResourceManager.GetString("WeekendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Weekly 的本地化字符串。
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 week(s) on: 的本地化字符串。
        /// </summary>
        internal static string WeeksOn {
            get {
                return ResourceManager.GetString("WeeksOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Yearly 的本地化字符串。
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
