//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm.Client.Common.GetDrugStoreDtl {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDistributionListFault", Namespace="ZSDrugStroe")]
    [System.SerializableAttribute()]
    public partial class GetDistributionListFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ZSDrugStroe", ConfigurationName="GetDrugStoreDtl.ZhongShanDrugStorePortType")]
    public interface ZhongShanDrugStorePortType {
        
        // CODEGEN: 命名空间 ZSDrugStroe 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetDistributionList", ReplyAction="ZSDrugStroe/ZhongShanDrugStorePortType/GetDistributionListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListFault), Action="ZSDrugStroe/ZhongShanDrugStorePortType/GetDistributionListFault", Name="GetDistributionListFault")]
        Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponse GetDistributionList(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetDistributionList", ReplyAction="ZSDrugStroe/ZhongShanDrugStorePortType/GetDistributionListResponse")]
        System.Threading.Tasks.Task<Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponse> GetDistributionListAsync(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributionListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributionList", Namespace="ZSDrugStroe", Order=0)]
        public Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequestBody Body;
        
        public GetDistributionListRequest() {
        }
        
        public GetDistributionListRequest(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ZSDrugStroe")]
    public partial class GetDistributionListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public GetDistributionListRequestBody() {
        }
        
        public GetDistributionListRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributionListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributionListResponse", Namespace="ZSDrugStroe", Order=0)]
        public Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponseBody Body;
        
        public GetDistributionListResponse() {
        }
        
        public GetDistributionListResponse(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ZSDrugStroe")]
    public partial class GetDistributionListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetDistributionListResponseBody() {
        }
        
        public GetDistributionListResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZhongShanDrugStorePortTypeChannel : Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZhongShanDrugStorePortTypeClient : System.ServiceModel.ClientBase<Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType>, Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType {
        
        public ZhongShanDrugStorePortTypeClient() {
        }
        
        public ZhongShanDrugStorePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZhongShanDrugStorePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZhongShanDrugStorePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZhongShanDrugStorePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponse Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType.GetDistributionList(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest request) {
            return base.Channel.GetDistributionList(request);
        }
        
        public string GetDistributionList(string data) {
            Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest inValue = new Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest();
            inValue.Body = new Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequestBody();
            inValue.Body.data = data;
            Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponse retVal = ((Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType)(this)).GetDistributionList(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponse> Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType.GetDistributionListAsync(Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest request) {
            return base.Channel.GetDistributionListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Orm.Client.Common.GetDrugStoreDtl.GetDistributionListResponse> GetDistributionListAsync(string data) {
            Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest inValue = new Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequest();
            inValue.Body = new Orm.Client.Common.GetDrugStoreDtl.GetDistributionListRequestBody();
            inValue.Body.data = data;
            return ((Orm.Client.Common.GetDrugStoreDtl.ZhongShanDrugStorePortType)(this)).GetDistributionListAsync(inValue);
        }
    }
}
